version: 2
  updates:
    - package-ecosystem: "github-actions"
      directory: "/.github/workflows"
      schedule:
        interval: "weekly"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "weekly"
    - package-ecosystem: "github-actions"
      directory: "/.github/workflows"
      schedule:
        interval: "weekly"
      allow:
        - dependency-name: "xu-cheng/latex-action"
