name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/main.tex     
      - name: Save PDF to output folder
        run: mkdir -p output && mv main.pdf output/
      - name: Convert PDF to PNG
        run: |
          sudo apt-get update && sudo apt-get install -y poppler-utils
          pdftoppm -png output/main.pdf > output/main.png
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Output Files
          path: output/
      - name: Add and commit outputs (PDF and PNG)
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add output/main.pdf output/main.png
          git commit -m "Add compiled PDF and PNG files"
      - name: Push changes to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
