name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/main.tex
      - name: Save PDF to output folder
        run: mkdir -p output && mv main.pdf output/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: output/main.pdf
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
